name: heroku-jupyter
dependencies:
  # bind notebook version (compatibility to pgcontents)
  # - notebook = 4
  - notebook
  - ipywidgets
  - requests
  # bind ipython version (compatibility to pgcontents)
  # - ipython = 5
  - ipython
  # bind tornado version (websocket problems)
  # - tornado = 4.5
  - tornado
  # get dependencies for pgcontents
  - certifi
  - click
  - cryptography 
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip:
    - pgcontents
    - numpy
    - matplotlib
    - trimesh
    - k3d
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
