name: heroku-jupyter
dependencies:
  # bind notebook version (compatibility to pgcontents)
  - notebook = 4
  - ipywidgets
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython = 5
  # bind tornado version (websocket problems)
  - tornado = 4.5
  # get dependencies for pgcontents
  - certifi
  - click
  - cryptography 
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip:
    - pgcontents
    - numpy
    - matplotlib
    - trimesh
    # - k3d
    - git+git://github.com/K3D-tools/K3D-jupyter.git@947d33212cb4d47bc15e6a70343380fac24c7f24
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
