#!/usr/bin/env bash

pgcontents init -l $DATABASE_URL --no-prompt

jupyter contrib nbextension install --user
jupyter nbextensions_configurator enable --user

jupyter nbextension install --py --sys-prefix k3d --user
jupyter nbextension enable --py --sys-prefix k3d --user

jupyter notebook \
	--no-browser --no-mathjax --ip=* --port $PORT \
	$JUPYTER_NOTEBOOK_ARGS \
	notebooks
